// splitright/lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByU3kyrrONM97N4zourz2OewzrzFxmMvQ',
    appId: '1:1096429438682:web:f0328de8b590dc06b4c7e3',
    messagingSenderId: '1096429438682',
    projectId: 'splitright-5a394',
    authDomain: 'splitright-5a394.firebaseapp.com',
    storageBucket: 'splitright-5a394.firebasestorage.app',
    measurementId: 'G-G9S1B2ZTMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR3xOIwhcCMG6RTN5dYHXIXbOtWwT8zZQ',
    appId: '1:1096429438682:android:80679fec695042bcb4c7e3',
    messagingSenderId: '1096429438682',
    projectId: 'splitright-5a394',
    storageBucket: 'splitright-5a394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dBQPiIduitaF86POaFtljibZU54Gp1I',
    appId: '1:1096429438682:ios:2ed8a2ea01ee3a95b4c7e3',
    messagingSenderId: '1096429438682',
    projectId: 'splitright-5a394',
    storageBucket: 'splitright-5a394.firebasestorage.app',
    iosBundleId: 'com.example.splitright',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2dBQPiIduitaF86POaFtljibZU54Gp1I',
    appId: '1:1096429438682:ios:2ed8a2ea01ee3a95b4c7e3',
    messagingSenderId: '1096429438682',
    projectId: 'splitright-5a394',
    storageBucket: 'splitright-5a394.firebasestorage.app',
    iosBundleId: 'com.example.splitright',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByU3kyrrONM97N4zourz2OewzrzFxmMvQ',
    appId: '1:1096429438682:web:06fb1332ec158348b4c7e3',
    messagingSenderId: '1096429438682',
    projectId: 'splitright-5a394',
    authDomain: 'splitright-5a394.firebaseapp.com',
    storageBucket: 'splitright-5a394.firebasestorage.app',
    measurementId: 'G-C8F7E1BPJE',
  );
}
